name: Feature request
description: Suggest an improvement to the site or the code
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve
      description: What are you trying to do that the site doesn't support today
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What you'd like to see, if you have something in mind
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
