// Serves the prerendered site from R2. CI syncs dist under env.ASSET_PREFIX, this Worker
// maps requests to objects. The box-contribute POST will branch here before the lookup.

import { type BoxContributeEnv, handleBoxContribute } from "./box-contribute";
import { cacheControl, contentType, notFoundKeys, prefixChain, resolveKey } from "./resolve";
import { classifyClient, hashVisitor, isBot } from "./visitor";

// `Env` (SITE_BUCKET/ASSET_PREFIX/GITHUB_APP_ID/etc) is the ambient global generated by
// wrangler (worker-configuration.d.ts, regenerate with `npm run wrangler:types`), a rename in
// wrangler.toml fails tsc here instead of drifting silently. BoxContributeEnv adds the
// secret-only members wrangler.toml can't see. Named WorkerEnv, not Env: BoxContributeEnv
// itself derives from the ambient Env, so an `interface Env extends BoxContributeEnv` merge
// here would make Env recursively reference itself.
// VISITOR_HASH_SALT is a `wrangler secret put` value too (see ADR-013), same reasoning.
type WorkerEnv = Env & BoxContributeEnv & { VISITOR_HASH_SALT?: string };

// Privacy-preserving visitor summary for one HTML document GET, see ADR-013. Never derived
// from anything logged raw: cf-connecting-ip and user-agent are read here and nowhere else.
async function visitorFields(
  request: Request,
  salt: string | undefined
): Promise<Record<string, unknown>> {
  // request.cf is typed as a union with RequestInitCfProperties (used for outgoing fetch()
  // init, not incoming requests), which collapses property access to `unknown`. An incoming
  // fetch handler's request.cf is always IncomingRequestCfProperties.
  const cf = request.cf as IncomingRequestCfProperties | undefined;
  const client = classifyClient(request.headers.get("user-agent"));
  const bot = isBot(cf?.botManagement);
  const category = cf?.verifiedBotCategory;
  const fields: Record<string, unknown> = { client, bot };
  if (bot && typeof category === "string" && category) fields.botCategory = category;
  if (cf?.country) fields.country = cf.country;
  if (salt) {
    const ip = request.headers.get("cf-connecting-ip") ?? "";
    const period = new Date().toISOString().slice(0, 7);
    fields.visitorHash = await hashVisitor(salt, period, ip, client);
  }
  return fields;
}

// Shared by every response path, including the hard-miss 404 below, so a request that can't
// even find 404.html in R2 still gets the same security posture as a normal hit.
function securityHeaders(): Headers {
  const headers = new Headers();
  headers.set("x-content-type-options", "nosniff");
  headers.set("x-frame-options", "SAMEORIGIN");
  headers.set("referrer-policy", "strict-origin-when-cross-origin");
  return headers;
}

export default {
  async fetch(request: Request, env: WorkerEnv, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);
    const start = Date.now();

    // Branches before the method gate below (which only permits GET/HEAD for the R2 read path).
    if (url.pathname === "/api/box-contribute" && request.method === "POST") {
      return handleBoxContribute(request, env);
    }

    if (request.method !== "GET" && request.method !== "HEAD") {
      console.log(
        JSON.stringify({ event: "method_not_allowed", method: request.method, path: url.pathname })
      );
      return new Response("Method Not Allowed", { status: 405, headers: { allow: "GET, HEAD" } });
    }

    // Cache production only: previews reuse a URL across pushes. Key on the pathname alone,
    // resolveKey ignores the query string, so /p?a=1 and /p?a=2 must not fragment the cache.
    const isProd = env.ASSET_PREFIX === "production";
    const cache = caches.default;
    const cacheKey = new Request(`${url.origin}${url.pathname}`);
    if (isProd) {
      const hit = await cache.match(cacheKey);
      if (hit) {
        console.log(
          JSON.stringify({ event: "cache_hit", path: url.pathname, ms: Date.now() - start })
        );
        return hit;
      }
    }

    const chain = prefixChain(env.ASSET_PREFIX);

    let status = 200;
    let servedKey = "";
    let object: R2ObjectBody | null = null;

    for (const prefix of chain) {
      servedKey = resolveKey(url.pathname, prefix);
      object = await env.SITE_BUCKET.get(servedKey);
      if (object) break;
    }

    if (!object) {
      status = 404;
      for (const candidate of notFoundKeys(url.pathname, chain)) {
        servedKey = candidate;
        object = await env.SITE_BUCKET.get(candidate);
        if (object) break;
      }
      if (!object) {
        console.log(
          JSON.stringify({
            event: "r2_miss_hard",
            path: url.pathname,
            prefix: env.ASSET_PREFIX,
            ms: Date.now() - start,
          })
        );
        const headers = securityHeaders();
        headers.set("content-type", "text/plain; charset=utf-8");
        headers.set("cache-control", "no-store");
        return new Response("Not found", { status: 404, headers });
      }
      console.log(
        JSON.stringify({
          event: "r2_404",
          path: url.pathname,
          key: servedKey,
          ms: Date.now() - start,
        })
      );
    }

    const headers = securityHeaders();
    headers.set(
      "content-type",
      contentType(servedKey) ?? object.httpMetadata?.contentType ?? "application/octet-stream"
    );
    headers.set("cache-control", status === 404 ? "no-store" : cacheControl(servedKey));
    if (object.httpEtag) headers.set("etag", object.httpEtag);

    // CSP scoped to HTML only.
    if (servedKey.endsWith(".html")) {
      headers.set(
        "content-security-policy",
        "default-src 'self'; script-src 'self' 'unsafe-inline' https://static.cloudflareinsights.com https://challenges.cloudflare.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self' https://cloudflareinsights.com; font-src 'self'; frame-src https://challenges.cloudflare.com; object-src 'none'; base-uri 'self'; form-action 'self'"
      );
    }

    // Answer a conditional request with a 304 instead of the full body when the etag matches.
    const ifNoneMatch = request.headers.get("if-none-match");
    if (status === 200 && object.httpEtag && ifNoneMatch?.includes(object.httpEtag)) {
      const extra304 =
        request.method === "GET" && servedKey.endsWith(".html")
          ? await visitorFields(request, env.VISITOR_HASH_SALT)
          : {};
      console.log(
        JSON.stringify({
          event: "not_modified",
          path: url.pathname,
          key: servedKey,
          ms: Date.now() - start,
          ...extra304,
        })
      );
      return new Response(null, { status: 304, headers });
    }

    const body = request.method === "HEAD" ? null : object.body;
    const response = new Response(body, { status, headers });

    if (isProd && status === 200 && request.method === "GET") {
      ctx.waitUntil(cache.put(cacheKey, response.clone()));
    }

    const extra =
      request.method === "GET" && servedKey.endsWith(".html")
        ? await visitorFields(request, env.VISITOR_HASH_SALT)
        : {};
    console.log(
      JSON.stringify({
        event: "served",
        path: url.pathname,
        key: servedKey,
        status,
        ms: Date.now() - start,
        ...extra,
      })
    );
    return response;
  },
};
